services:
  db:
    image: postgres:14.22
    restart: always
    shm_size: 128mb
    networks:
      - resr
    environment:
      POSTGRES_PASSWORD: ${DB__Password}
      POSTGRES_USER: ${DB__Username}
      POSTGRES_DB: ${DB__Database}
    volumes:
      - resr-db:/var/lib/postgresql/data/

  resr-api:
    build:
      context: .
      dockerfile: src/Presentation/Api/Dockerfile
    ports:
      - 7151:80
      - 7150:443
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORTS: "443"
    command: ["-n"]
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - db

networks:
  resr:

volumes:
  resr-db: