services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "${DB_Port}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_Password}
      POSTGRES_USER: ${DB_Username}
      POSTGRES_DB: ${DB_Database}

  smtp:
    image: maildev/maildev
    environment:
      MAILDEV_SMTP_PORT: 1026
    ports:
      - "3000:1080"         # Interface web
      - "${Smtp_Port}:1026" # SMTP