// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReSR.Infrastructure.Core;

#nullable disable

namespace ReSR.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReSR.Domain.Aggregates.Accounts.Manager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Permissions")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Accounts.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnonymizationProcessStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Permissions")
                        .HasColumnType("smallint");

                    b.Property<bool>("Suspended")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Categories.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Messages.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnsweredCommentId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommentedResourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SentById")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AnsweredCommentId");

                    b.HasIndex("CommentedResourceId");

                    b.HasIndex("SentById");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Messages.PrivateMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("QuotedResourceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SentById")
                        .HasColumnType("bigint");

                    b.Property<long>("SentToId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuotedResourceId");

                    b.HasIndex("SentById");

                    b.HasIndex("SentToId");

                    b.ToTable("PrivateMessages");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.QuizSessions.QuizSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("QuizSessions");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Resources.Resource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Relationships")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Title", "CategoryId")
                        .IsUnique();

                    b.ToTable("Resource");

                    b.HasDiscriminator().HasValue("Resource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ResourceUser", b =>
                {
                    b.Property<long>("LikedById")
                        .HasColumnType("bigint");

                    b.Property<long>("LikesId")
                        .HasColumnType("bigint");

                    b.HasKey("LikedById", "LikesId");

                    b.HasIndex("LikesId");

                    b.ToTable("Likes", (string)null);
                });

            modelBuilder.Entity("ResourceUser1", b =>
                {
                    b.Property<long>("BookmarkedById")
                        .HasColumnType("bigint");

                    b.Property<long>("BookmarksId")
                        .HasColumnType("bigint");

                    b.HasKey("BookmarkedById", "BookmarksId");

                    b.HasIndex("BookmarksId");

                    b.ToTable("Bookmarks", (string)null);
                });

            modelBuilder.Entity("ResourceUser2", b =>
                {
                    b.Property<long>("ExploitedById")
                        .HasColumnType("bigint");

                    b.Property<long>("ExploitsId")
                        .HasColumnType("bigint");

                    b.HasKey("ExploitedById", "ExploitsId");

                    b.HasIndex("ExploitsId");

                    b.ToTable("Exploits", (string)null);
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<long>("LikedById")
                        .HasColumnType("bigint");

                    b.Property<long>("LikedUsersId")
                        .HasColumnType("bigint");

                    b.HasKey("LikedById", "LikedUsersId");

                    b.HasIndex("LikedUsersId");

                    b.ToTable("Friends", (string)null);
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Resources.QuizResource", b =>
                {
                    b.HasBaseType("ReSR.Domain.Aggregates.Resources.Resource");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("QuizResource");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Resources.TextResource", b =>
                {
                    b.HasBaseType("ReSR.Domain.Aggregates.Resources.Resource");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Resource", t =>
                        {
                            t.Property("Content")
                                .HasColumnName("TextResource_Content");
                        });

                    b.HasDiscriminator().HasValue("TextResource");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Messages.Comment", b =>
                {
                    b.HasOne("ReSR.Domain.Aggregates.Messages.Comment", "AnsweredComment")
                        .WithMany("Answers")
                        .HasForeignKey("AnsweredCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReSR.Domain.Aggregates.Resources.Resource", "CommentedResource")
                        .WithMany("Comments")
                        .HasForeignKey("CommentedResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReSR.Domain.Aggregates.Accounts.User", "SentBy")
                        .WithMany()
                        .HasForeignKey("SentById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ReSR.Domain.Aggregates.Messages.ValueObjects.Report", "Reports", b1 =>
                        {
                            b1.Property<long>("CommentId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("ReportedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<long>("ReportedById")
                                .HasColumnType("bigint");

                            b1.HasKey("CommentId", "Id");

                            b1.HasIndex("ReportedById");

                            b1.ToTable("Report");

                            b1.WithOwner()
                                .HasForeignKey("CommentId");

                            b1.HasOne("ReSR.Domain.Aggregates.Accounts.User", "ReportedBy")
                                .WithMany()
                                .HasForeignKey("ReportedById")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("ReportedBy");
                        });

                    b.Navigation("AnsweredComment");

                    b.Navigation("CommentedResource");

                    b.Navigation("Reports");

                    b.Navigation("SentBy");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Messages.PrivateMessage", b =>
                {
                    b.HasOne("ReSR.Domain.Aggregates.Resources.Resource", "QuotedResource")
                        .WithMany()
                        .HasForeignKey("QuotedResourceId");

                    b.HasOne("ReSR.Domain.Aggregates.Accounts.User", "SentBy")
                        .WithMany()
                        .HasForeignKey("SentById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReSR.Domain.Aggregates.Accounts.User", "SentTo")
                        .WithMany()
                        .HasForeignKey("SentToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuotedResource");

                    b.Navigation("SentBy");

                    b.Navigation("SentTo");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.QuizSessions.QuizSession", b =>
                {
                    b.HasOne("ReSR.Domain.Aggregates.Resources.QuizResource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ReSR.Domain.Aggregates.QuizSessions.ValueObjects.QuizParticipation", "Participations", b1 =>
                        {
                            b1.Property<long>("QuizSessionId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("Score")
                                .HasColumnType("integer");

                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.HasKey("QuizSessionId", "Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("QuizParticipation");

                            b1.WithOwner()
                                .HasForeignKey("QuizSessionId");

                            b1.HasOne("ReSR.Domain.Aggregates.Accounts.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.Navigation("Participations");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Resources.Resource", b =>
                {
                    b.HasOne("ReSR.Domain.Aggregates.Categories.Category", "Category")
                        .WithMany("Resources")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReSR.Domain.Aggregates.Accounts.User", "Owner")
                        .WithMany("OwnedResources")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ResourceUser", b =>
                {
                    b.HasOne("ReSR.Domain.Aggregates.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("LikedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReSR.Domain.Aggregates.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("LikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResourceUser1", b =>
                {
                    b.HasOne("ReSR.Domain.Aggregates.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("BookmarkedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReSR.Domain.Aggregates.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("BookmarksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResourceUser2", b =>
                {
                    b.HasOne("ReSR.Domain.Aggregates.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("ExploitedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReSR.Domain.Aggregates.Resources.Resource", null)
                        .WithMany()
                        .HasForeignKey("ExploitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("ReSR.Domain.Aggregates.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("LikedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReSR.Domain.Aggregates.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("LikedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Resources.QuizResource", b =>
                {
                    b.OwnsMany("ReSR.Domain.Aggregates.Resources.ValueObjects.QuizQuestion", "Questions", b1 =>
                        {
                            b1.Property<long>("QuizResourceId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("QuizResourceId", "Id");

                            b1.ToTable("QuizQuestion");

                            b1.WithOwner()
                                .HasForeignKey("QuizResourceId");

                            b1.OwnsMany("ReSR.Domain.Aggregates.Resources.ValueObjects.QuizAnswer", "Answers", b2 =>
                                {
                                    b2.Property<long>("QuizQuestionQuizResourceId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("QuizQuestionId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Content")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<bool>("IsCorrect")
                                        .HasColumnType("boolean");

                                    b2.HasKey("QuizQuestionQuizResourceId", "QuizQuestionId", "Id");

                                    b2.ToTable("QuizAnswer");

                                    b2.WithOwner()
                                        .HasForeignKey("QuizQuestionQuizResourceId", "QuizQuestionId");
                                });

                            b1.Navigation("Answers");
                        });

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Accounts.User", b =>
                {
                    b.Navigation("OwnedResources");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Categories.Category", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Messages.Comment", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ReSR.Domain.Aggregates.Resources.Resource", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
